CREATE TABLE playbyplay (
        "Player" TEXT,
        "Pos" TEXT,
        "Age" SMALLINT,
        "Tm" TEXT,
        "G" SMALLINT,
        "MP" SMALLINT,
        "PG_Pc" DECIMAL,
        "SG_Pc" DECIMAL,
        "SF_Pc" DECIMAL,
        "PF_Pc" DECIMAL,
        "C_Pc" DECIMAL,
        "PMP100_OnCourt" DECIMAL,
        "PMP100_On_Off" DECIMAL,
        "BadPassTO" SMALLINT,
        "LostBallTO" SMALLINT,
        "FoulC_Shoot" SMALLINT,
        "FoulC_Off" SMALLINT,
        "FoulD_Shoot" SMALLINT,
        "FoulD_Off" SMALLINT,
        "PGA" SMALLINT,
        "And1" SMALLINT,
        "Blkd" SMALLINT,
        "Season" SMALLINT,
        "PlayerID" TEXT
)

CREATE TABLE playerTable (
        'PlayerID' TEXT,
        'Height' TEXT,
        'Weight' TEXT,
        'BirthDate' DATE,
        'Country' TEXT,
        'State' TEXT,
        'College' TEXT,
        'RecruitYr' SMALLINT,
        'RecruitRank' SMALLINT,
        'DraftYear' SMALLINT,
        'Pick' SMALLINT
)