CREATE TABLE playbyplay (
        "Player" TEXT,
        "Pos" TEXT,
        "Age" BIGINT,
        "Tm" TEXT,
        "G" BIGINT,
        "MP" BIGINT,
        "PG_Pc" FLOAT,
        "SG_Pc" FLOAT,
        "SF_Pc" FLOAT,
        "PF_Pc" FLOAT,
        "C_Pc" FLOAT,
        "PMP100_OnCourt" FLOAT,
        "PMP100_On_Off" FLOAT,
        "BadPassTO" BIGINT,
        "LostBallTO" BIGINT,
        "FoulC_Shoot" BIGINT,
        "FoulC_Off" BIGINT,
        "FoulD_Shoot" BIGINT,
        "FoulD_Off" BIGINT,
        "PGA" BIGINT,
        "And1" BIGINT,
        "Blkd" BIGINT,
        "Season" BIGINT,
        "PlayerID" TEXT,
        "Country" TEXT
)