CREATE TABLE playerTable (
        "Name" TEXT PRIMARY KEY,
        "Height" TEXT,
        "Weight" TEXT,
        "BirthDate" DATE,
        "Country" TEXT,
        "State" TEXT,
        "College" TEXT,
        "RecruitYr" SMALLINT,
        "RecruitRank" SMALLINT,
        "DraftYear" SMALLINT,
        "Pick" SMALLINT
);

CREATE TABLE totals (
        "Player" TEXT,
        "Pos" TEXT,
        "Age" SMALLINT,
        "Tm" TEXT,
        "G" SMALLINT,
        "GS" SMALLINT,
        "MP" SMALLINT,
        "FG" SMALLINT,
        "FGA" SMALLINT,
        "FGPc" DECIMAL,
        "_3P" SMALLINT,
        "_3PA" SMALLINT,
        "_3PTPc" DECIMAL,
        "_2P" SMALLINT,
        "_2PA" SMALLINT,
        "_2PTPc" DECIMAL,
        "eFGPc" DECIMAL,
        "FT" SMALLINT,
        "FTA" SMALLINT,
        "FTPc" DECIMAL,
        "ORB" SMALLINT,
        "DRB" SMALLINT,
        "TRB" SMALLINT,
        "AST" SMALLINT,
        "STL" SMALLINT,
        "BLK" SMALLINT,
        "TOV" SMALLINT,
        "PF" SMALLINT,
        "PTS" SMALLINT,
        "Season" SMALLINT,
        "PlayerID" TEXT,
        PRIMARY KEY ("PlayerID", "Season"),
        FOREIGN KEY ("PlayerID")
            REFERENCES playerTable ("PlayerID")

);

CREATE TABLE per36 (
        "Player" TEXT,
        "Pos" TEXT,
        "Age" SMALLINT,
        "Tm" TEXT,
        "G" SMALLINT,
        "GS" SMALLINT,
        "MP" DECIMAL,
        "FG" DECIMAL,
        "FGA" DECIMAL,
        "FGPc" DECIMAL,
        "_3P" DECIMAL,
        "_3PA" DECIMAL,
        "_3PTPc" DECIMAL,
        "_2P" DECIMAL,
        "_2PA" DECIMAL,
        "_2PTPc" DECIMAL,
        "eFGPc" DECIMAL,
        "FT" DECIMAL,
        "FTA" DECIMAL,
        "FTPc" DECIMAL,
        "ORB" DECIMAL,
        "DRB" DECIMAL,
        "TRB" DECIMAL,
        "AST" DECIMAL,
        "STL" DECIMAL,
        "BLK" DECIMAL,
        "TOV" DECIMAL,
        "PF" DECIMAL,
        "PTS" DECIMAL,
        "Season" SMALLINT,
        "PlayerID" TEXT,
        PRIMARY KEY ("PlayerID", "Season"),
        FOREIGN KEY ("PlayerID")
            REFERENCES playerTable ("PlayerID")
);

CREATE TABLE pergame (
        "Player" TEXT,
        "Pos" TEXT,
        "Age" SMALLINT,
        "Tm" TEXT,
        "G" SMALLINT,
        "GS" SMALLINT,
        "MP" DECIMAL,
        "FG" DECIMAL,
        "FGA" DECIMAL,
        "FGPc" DECIMAL,
        "_3P" DECIMAL,
        "_3PA" DECIMAL,
        "_3PTPc" DECIMAL,
        "_2P" DECIMAL,
        "_2PA" DECIMAL,
        "_2PTPc" DECIMAL,
        "eFGPc" DECIMAL,
        "FT" DECIMAL,
        "FTA" DECIMAL,
        "FTPc" DECIMAL,
        "ORB" DECIMAL,
        "DRB" DECIMAL,
        "TRB" DECIMAL,
        "AST" DECIMAL,
        "STL" DECIMAL,
        "BLK" DECIMAL,
        "TOV" DECIMAL,
        "PF" DECIMAL,
        "PTS" DECIMAL,
        "Season" SMALLINT,
        "PlayerID" TEXT,
        PRIMARY KEY ("PlayerID", "Season"),
        FOREIGN KEY ("PlayerID")
            REFERENCES playerTable ("PlayerID")
);

CREATE TABLE advanced (
        "Player" TEXT,
        "Pos" TEXT,
        "Age" SMALLINT,
        "Tm" TEXT,
        "G" SMALLINT,
        "MP" SMALLINT,
        "PER" DECIMAL,
        "TS" DECIMAL,
        "Ar3P" DECIMAL,
        "FTr" DECIMAL,
        "ORB" DECIMAL,
        "DRB" DECIMAL,
        "TRB" DECIMAL,
        "AST" DECIMAL,
        "STL" DECIMAL,
        "BLK" DECIMAL,
        "TOV" DECIMAL,
        "USG" DECIMAL,
        "OWS" DECIMAL,
        "DWS" DECIMAL,
        "WS" DECIMAL,
        "WS_48" DECIMAL,
        "OBPM" DECIMAL,
        "DBPM" DECIMAL,
        "BPM" DECIMAL,
        "VORP" DECIMAL,
        "Season" SMALLINT,
        "PlayerID" TEXT,
        PRIMARY KEY ("PlayerID", "Season"),
        FOREIGN KEY ("PlayerID")
            REFERENCES playerTable ("PlayerID")
);

CREATE TABLE shooting (
        "Player" TEXT,
        "Pos" TEXT,
        "Age" SMALLINT,
        "Tm" TEXT,
        "G" SMALLINT,
        "MP" SMALLINT,
        "FGP" DECIMAL,
        "Dist" DECIMAL,
        "FGAxDist_2P" DECIMAL,
        "FGAxDist_0_3" DECIMAL,
        "FGAxDist_3_10" DECIMAL,
        "FGAxDist_10_16" DECIMAL,
        "FGAxDist_16_3P" DECIMAL,
        "FGAxDist_3P" DECIMAL,
        "FGPxDist_2P" DECIMAL,
        "FGPxDist_0_3" DECIMAL,
        "FGPxDist_3_10" DECIMAL,
        "FGPxDist_10_16" DECIMAL,
        "FGPxDist_16_3P" DECIMAL,
        "FGPxDist_3P" DECIMAL,
        "AstPc_2P" DECIMAL,
        "AstPc_3P" DECIMAL,
        "Dunks_FGA" DECIMAL,
        "Num_Dunks" SMALLINT,
        "Corner_3PFGA" DECIMAL,
        "Corner_3PPc" DECIMAL,
        "Heaves_Att" SMALLINT,
        "Heaves_Made" SMALLINT,
        "Season" SMALLINT,
        "PlayerID" TEXT,
        PRIMARY KEY ("PlayerID", "Season"),
        FOREIGN KEY ("PlayerID")
            REFERENCES playerTable ("PlayerID")
);

CREATE TABLE playbyplay (
        "Player" TEXT,
        "Pos" TEXT,
        "Age" SMALLINT,
        "Tm" TEXT,
        "G" SMALLINT,
        "MP" SMALLINT,
        "PG_Pc" DECIMAL,
        "SG_Pc" DECIMAL,
        "SF_Pc" DECIMAL,
        "PF_Pc" DECIMAL,
        "C_Pc" DECIMAL,
        "PMP100_OnCourt" DECIMAL,
        "PMP100_On_Off" DECIMAL,
        "BadPassTO" SMALLINT,
        "LostBallTO" SMALLINT,
        "FoulC_Shoot" SMALLINT,
        "FoulC_Off" SMALLINT,
        "FoulD_Shoot" SMALLINT,
        "FoulD_Off" SMALLINT,
        "PGA" SMALLINT,
        "And1" SMALLINT,
        "Blkd" SMALLINT,
        "Season" SMALLINT,
        "PlayerID" TEXT,
        PRIMARY KEY ("PlayerID", "Season"),
        FOREIGN KEY ("PlayerID")
            REFERENCES playerTable ("PlayerID")
);

CREATE TABLE per_poss (
        "Player" TEXT,
        "Pos" TEXT,
        "Age" SMALLINT,
        "Tm" TEXT,
        "G" SMALLINT,
        "GS" SMALLINT,
        "MP" SMALLINT,
        "FG" DECIMAL,
        "FGA" DECIMAL,
        "FGPc" DECIMAL,
        "_3P" DECIMAL,
        "_3PA" DECIMAL,
        "_3PTPc" DECIMAL,
        "_2P" DECIMAL,
        "_2PA" DECIMAL,
        "_2PTPc" DECIMAL,
        "FT" DECIMAL,
        "FTA" DECIMAL,
        "FTPc" DECIMAL,
        "ORB" DECIMAL,
        "DRB" DECIMAL,
        "TRB" DECIMAL,
        "AST" DECIMAL,
        "STL" DECIMAL,
        "BLK" DECIMAL,
        "TOV" DECIMAL,
        "PF" DECIMAL,
        "PTS" DECIMAL,
        "ORtg" SMALLINT,
        "DRtg" SMALLINT,
        "Season" SMALLINT,
        "PlayerID" TEXT,
        PRIMARY KEY ("PlayerID", "Season"),
        FOREIGN KEY ("PlayerID")
            REFERENCES playerTable ("PlayerID")
);

